on: [pull_request]

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@master"
        with:
          buildkite_api_access_token: "bkua_2d8f08a3a986f9c87da68e5d5cfac22a98ee3243"
          pipeline: "ibm-14/ppc64le-build"
          message:  ":github: Triggered from a GitHub Action"
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build_meta_data: '{"FOO": "bar"}'
          ignore_pipeline_branch_filter: true     
          send_pull_request: true
          wait: true
          wait_interval: 10
